name: Deploy MERN App to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install --prefix backend
          npm install --prefix frontend

      - name: Build frontend
        run: |
          npm run build --prefix frontend
          
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "mern-cicd-demo-app"
          heroku_email: "adnagee@gmail.com"
          branch: main
        env: 
          HD_SKIP_APP_CREATION: true
