name: Test MERN App on PR

on:
  workflow_run:
    workflows: ["Auto PR: Dev to Main"]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend deps & run tests
        working-directory: backend
        run: |
          npm install
          npm test

      - name: Install frontend deps & run tests
        working-directory: frontend
        run: |
          npm install
          npm test -- --watchAll=false

      - name: Authenticate with GitHub CLI
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        
      - name: Get PR number
        id: get_pr
        run: |
         PR_NUMBER=$(gh pr list --state open --head dev --base main --json number -q '.[0].number')
         echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Merge PR if tests pass
        run: |
          gh pr merge $PR_NUMBER --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Force push main to trigger deploy workflow
        run: |
          git fetch origin main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}